# Generated by Django 4.0 on 2022-01-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_age_range'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='age_range',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 10), ('age__lte', 20)), name='age contraint'),
        ),
    ]
