# Generated by Django 4.0 on 2022-01-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_age_range_student_age contraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='age contraint',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 10), ('age__lte', 20)), name='age_10_20'),
        ),
    ]
